export const QuizData = {
  g1: [
    {
      id: 0,
      question:
        '1215 yılında imzalanan Magna Carta sözleşmesi hangi ülke ile imzalanmıştır',
      options: ['İspanya', 'Almanya', 'İngiltere', 'Fransa', 'İtalya'],
      answer: 'İngiltere',
    },
    {
      id: 1,
      question: 'Galatasaray hangi yıl UEFA kupasını kazanmıştır',
      options: ['2000', '2001', '2002', '2003', '2005'],
      answer: '2000',
    },
    {
      id: 2,
      question: 'Kıbrıs barış harekatı hangi yılda yapılmıştır',
      options: ['1970', '1972', '1973', '1974', '1975'],
      answer: '1974',
    },
    {
      id: 3,
      question:
        'ABD Başkanlarından John Fitzgerald Kennedy`e suaikast düzenleyerek öldüren kimdir?',
      options: [
        'Lee Harvey Oswald',
        'Clay Shaw',
        'Jack Roby',
        'John Wilkes',
        'Micheal Keaton',
      ],
      answer: 'Lee Harvey Oswald',
    },
    {
      id: 4,
      question: 'Fransız İhtilali kaç yılında gerçekleştirilmiştir? ',
      options: [
        '1780-1785',
        '1786-1789',
        '1789-1799',
        '1790-1799',
        '1790-1796',
      ],
      answer: '1789-1799',
    },
    {
      id: 5,
      question: 'Kuyucaklı Yusuf adlı eser kime aittir? ',
      options: [
        'Yaşar Kemal',
        'Orhan Pamuk',
        'Ziya Gökalp',
        'Nabizade Nazım',
        'Sabahattin Ali',
      ],
      answer: 'Sabahattin Ali',
    },
    {
      id: 6,
      question: 'Lale devri dönemi hangi padişah döneminde yaşanmıştır?',
      options: ['1.Ahmet', '2.Ahmet', '3.Ahmet', '4.Murad', 'Abdülhamit'],
      answer: '3.Ahmet',
    },
    {
      id: 7,
      question: 'Fas`ın başkenti aşağıdakilerden hangisidir?',
      options: ['Kahire', 'Ankara', 'Rabat', 'Kasablanca', 'Fes'],
      answer: 'Rabat',
    },
    {
      id: 8,
      question:
        '2002 Eurovision şarkı yarışması birincisi aşağıdakilerden hangisidir?',
      options: [
        'Normunds Rutulis',
        'Marija Naumova',
        'Aisha',
        'Sertap Erener',
        'Linda Leen',
      ],
      answer: 'Marija Naumova',
    },
    {
      id: 9,
      question:
        '1994`te sadece 3 kaldırış yaparak dünya rekoru kıran dünyaca ünlü halterci aşağıdakilerden hangisidir?',
      options: [
        'Halil Mutlu',
        'Nurcan Taylan',
        'Naim Süleymanoğlu',
        'Sibel Özkan',
        'Gülbeyi Akti',
      ],
      answer: 'Naim Süleymanoğlu',
    },
  ],
  g2: [
    {
      id: 0,
      question: 'Aşağıdaki ülkelerin hangisinin bayrağında yıldız yoktur?',
      options: ['Singapur', 'Moritanya', 'Maldivler', 'Hırvatistan', 'Türkiye'],
      answer: 'Maldivler',
    },
    {
      id: 1,
      question: 'Dünya`nın en uzun savunma duvarı aşağıdakilerden hangisidir?',
      options: [
        'Berlin Duvarı',
        'Troya Duvarları',
        'Çin Seddi',
        'Toledo Surları',
        'Ağlama Duvarı',
      ],
      answer: 'Çin Seddi',
    },
    {
      id: 2,
      question: 'Aziz Sancar Nobel Kimya ödülünü kaç yılında almıştır?',
      options: ['2019', '2018', '2017', '2016', '2015'],
      answer: '2015',
    },
    {
      id: 3,
      question:
        'En iyi film Oscar`ını 1991`de kazanan ilk ve tek gerilim filmi aşağıdakilerden hangisidir?',
      options: [
        'The Purge',
        'Kuzuların Sessizliği',
        'Evdeki Düşman',
        'Kaçak',
        'Parazit',
      ],
      answer: 'Kuzuların Sessizliği',
    },
    {
      id: 4,
      question:
        'Yüzüklerin Efendisi adlı Fantastik filmin yönetmeni aşağıdakilerden hangisidir?',
      options: [
        'Peter Jackson',
        'David Fincher',
        'Woody Allen',
        'Tim Burton',
        'J.J. Abrams',
      ],
      answer: 'Peter Jackson',
    },
    {
      id: 5,
      question: '1982 Anayasasına göre;yeni bir il kurulması hangi yolla olur?',
      options: [
        'Anayasa değişikliği ile',
        'Bakanlar kurulu kararıyla',
        'Kanunla',
        'Cumhurbaşkanı kararıyla',
        'iç işleri bakanlığının kararıyla',
      ],
      answer: 'Kanunla',
    },
    {
      id: 6,
      question: 'Türkiye`nin ilk Safari parkı hangi ilimizde açılmıştır?',
      options: ['Malatya', 'Bayburt', 'İstanbul', 'Gaziantep', 'İzmir'],
      answer: 'Gaziantep',
    },
    {
      id: 7,
      question:
        'Türkiye`nin en büyük kış ve doğa sporları merkezi olan Uludağ`ın eski adı aşağıdakilerden hangisidir?',
      options: ['Keşişdağ', 'Ulukuş Dağı', 'Buzdağ', 'Yeşil Dağ', 'Gri Dağ'],
      answer: 'Keşişdağ',
    },
    {
      id: 8,
      question: 'Gece ve gündüz eşitliğine ne ad verilir?',
      options: ['ekinoks', 'dönence', 'tutulma', 'paradoks', 'cemre'],
      answer: 'ekinoks',
    },
    {
      id: 9,
      question: 'Amerika`nın 5. Başkanı aşağıdakilerden hangisidir?',
      options: [
        'George Washington',
        'Thomas Jefferson',
        'James Madison',
        'James Monroe',
        'Bill Clinton',
      ],
      answer: 'James Madison',
    },
  ],
  g3: [
    {
      id: 0,
      question: 'Dünyadaki ilk alışveriş sitesi hangisidir?',
      options: [
        'Trendyol',
        'Hepsiburada',
        'Ali expres',
        'Amazon',
        'gittigidiyor',
      ],
      answer: 'Amazon',
    },
    {
      id: 1,
      question: 'Altın Koza film festivali hangi ilimizde yapılır?',
      options: ['Antalya', 'İzmir', 'Adana', 'Gaziantep', 'Mersin'],
      answer: 'Adana',
    },
    {
      id: 2,
      question:
        'Eski Başbakanlardan Adnan Menderes hangi alanda eğitim almıştır?',
      options: ['Jeoloji', 'Hukuk', 'Tıp', 'Fizik', 'Güzel Sanatlar'],
      answer: 'Hukuk',
    },
    {
      id: 3,
      question: 'Zerzevat nedir?',
      options: ['Giysi', 'Meyve', 'Ayakkabı', 'Sebze', 'Para'],
      answer: 'Sebze',
    },
    {
      id: 4,
      question:
        'Akdeniz`i Kızıldeniz`e bağlayan ve Mısır`ın Osmanlı idaresinde olduğu dönemde açılan kanal aşağıdakilerden hangisidir?',
      options: [
        'Panama Kanalı',
        'Hürmüz Boğazı',
        'Süveyş Kanalı',
        'Cebelitarık Boğazı',
        'Kiel Kanalı',
      ],
      answer: 'Süveyş Kanalı',
    },
    {
      id: 5,
      question: 'Nobel ödüllerini veren ülke hangisidir?',
      options: ['İsveç', 'İngiltere', 'İspanya', 'Fransa', 'İtalya'],
      answer: 'İsveç',
    },
    {
      id: 6,
      question: '50 TL arka yüzünde kimin görseli vardır?',
      options: [
        'Atatürk',
        'Yunus Emre',
        'Cahit Arf',
        'Fatma Aliye',
        'Mimar Kemalettin',
      ],
      answer: 'Fatma Aliye',
    },
    {
      id: 7,
      question:
        'Türkiye Tıp tarihinde ilk yüz nakli operasyonu hangi üniversitede gerçekleştirilmiştir?',
      options: [
        'Boğaziçi Üniversitesi',
        'Dokuz Eylül Üniversitesi',
        'Çukurova Üniversitesi',
        'Akdeniz Üniversitesi',
        'Anadolu Üniversitesi',
      ],
      answer: 'Akdeniz Üniversitesi',
    },
    {
      id: 8,
      question: 'Dünya Sağlık Örgütü (WHO) kaç yılında kurulmuştur?',
      options: ['1942', '1944', '1946', '1948', '1950'],
      answer: '1948',
    },
    {
      id: 9,
      question: 'BM`nin resmi dili değildir?',
      options: ['Arapça', 'Çince', 'Fransızca', 'İngilizce', 'Farsça'],
      answer: 'Farsça',
    },
  ],
  g4: [
    {
      id: 0,
      question:
        'Aşağıdakilerden hangisi Türkiye`nin üyesi olduğu bir örgüt değildir?',
      options: ['NATO', 'WTO', 'BAP', 'G-20', 'OPEC'],
      answer: 'OPEC',
    },
    {
      id: 1,
      question:
        'Bir BM kurumu olan UNESCO`nun açılımında aşağıdaki sözcüklerden hangisi yoktur?',
      options: ['Çocuk', 'Eğitim', 'Bilim', 'Kültür', 'Sağlık'],
      answer: 'Çocuk',
    },
    {
      id: 2,
      question:
        'Tatar yayı olarak da bilinen ve Orta çağda yaygın olarak kullanılan uzak mesafe silahı aşağıdakilerden hangisidir?',
      options: ['Mızrak', 'Topuz', 'Kama', 'Tüfek', 'Arbalet'],
      answer: 'Arbalet',
    },
    {
      id: 3,
      question:
        'Aşağıdakilerden hangisi Güney Amerika tatiline çıkınca görebileceğiniz sıradağdır?',
      options: ['Kilimanjaro', 'And', 'Mauna Kea', 'Alp', 'Fuji'],
      answer: 'And',
    },
    {
      id: 4,
      question:
        'Karşılıklı yer değiştirme anlamında kullanılan kelime aşağıdakilerden hangisidir?',
      options: ['Asayiş', 'Becayiş', 'Nümayiş', 'Sitayiş', 'Fitayiş'],
      answer: 'Becayiş',
    },
    {
      id: 5,
      question:
        'Dünyanın en büyük yü ölçümüne sahip şehri aşağıdakilerden hangisidir?',
      options: ['Roma', 'Washington', 'Honolulu', 'Hong kong', 'Berlin'],
      answer: 'Honolulu',
    },
    {
      id: 6,
      question: 'Avrupanın en yüksek yanardağı aşağıdakilerden hangisidir?',
      options: ['Vezüv', 'Elbruz', 'Lewotolo', 'Pompei', 'Etna'],
      answer: 'Etna',
    },
    {
      id: 7,
      question:
        '15 Temmuz darbe girişimi sırasında şehit olan Ömer Halisdemir nerelidir? ',
      options: ['Konya', 'Kayseri', 'Niğde', 'Adana', 'Hakkari'],
      answer: 'Niğde',
    },
    {
      id: 8,
      question: 'Rus edebiyatının hekim yaarı kimdir?',
      options: ['Dostoyevski', 'Tolstoy', 'Gogol', 'Çehov', 'sheakspre'],
      answer: 'Çehov',
    },
    {
      id: 9,
      question:
        '1982 Nobel edebiyat ödülünü alan Kolombiyalı yazar Gabriel Garcia Marquez`in ödül alan kitabı aşağıdakilerden hangisidir?',
      options: [
        'Anlatmak için yaşamak',
        'Yüzyıllık Yalnızlık',
        'Kırmızı Pazartesi',
        'Şer Saati',
        'Doğru Avrupada Yolculuk',
      ],
      answer: 'Yüzyıllık Yalnızlık',
    },
  ],
  g5: [
    {
      id: 0,
      question:
        '1071`de yapılan Malazgirt savaşı ile anadolunun kapılarını Türklere açan Selçuklu Sultanı kimdir?',
      options: [
        'Sultan Alparslan',
        'Melikşah',
        'Çağrı Bey',
        'Berkyaruk',
        'Muhammet Tapar',
      ],
      answer: 'Sultan Alparslan',
    },
    {
      id: 1,
      question: 'Kızınca tüküren hayvan aşağıdakilerden hangisidir?',
      options: ['Lama', 'Aslan', 'Balık', 'Kuş', 'Fil'],
      answer: 'Lama',
    },
    {
      id: 2,
      question:
        'Gerçeküstücülük anlamına gelen akım aşağıdakilerden hangisidir?',
      options: ['Kübizm', 'Fovizm', 'Sürrealizm', 'Faşizm', 'İzlenimcilik'],
      answer: 'Sürrealizm',
    },
    {
      id: 3,
      question: 'Çocuk hakları günü hangi tarihte kutlanmaktadır?',
      options: ['20 Temmuz', '20 Kasım', '20 Aralık', '20 Nisan', '20 Ocak'],
      answer: '20 Kasım',
    },
    {
      id: 4,
      question:
        'Kullandığımız kağıt banknotların üzerinde aşağıdaki cümlelerden hangisi yazmaktadır?',
      options: [
        '14 Ocak 1933 tarih ve 1211 sayılı kanuna göre çıkarılmıştır',
        '14 Ocak 1970 tarih ve 1211 sayılı kanuna göre çıkarılmıştır',
        '14 Ocak 1950 tarih ve 1211 sayılı kanuna göre çıkarılmıştır',
        '14 Ocak 1965 tarih ve 1211 sayılı kanuna göre çıkarılmıştır',
      ],
      answer: '14 Ocak 1970 tarih ve 1211 sayılı kanuna göre çıkarılmıştır',
    },
    {
      id: 5,
      question:
        'Uyurken birbirlerinden ayrı düşmemek için el ele tutuşan hayvan hangisidir?',
      options: ['Su Samuru', 'Penguen', 'kirpi', 'Balina', 'köpek'],
      answer: 'Su Samuru',
    },
    {
      id: 6,
      question:
        '0`dan 96 km hıza 3 saniyede erişen hayvan aşağıdakilerden hangisidir?',
      options: ['Leopar', 'Jaguar', 'Çita', 'Köpek Balığı', 'Kartal'],
      answer: 'Çita',
    },
    {
      id: 7,
      question: 'Hayatları boyunca tek eşi olan deniz canlısı hangisidir?',
      options: [
        'Deniz Yıldızı',
        'Deniz Anası',
        'Deniz Atı',
        'Fok Balığı',
        'Balina',
      ],
      answer: 'Deniz Atı',
    },
    {
      id: 8,
      question: '4 yıl boyunca uykuda kalabilen hayvan hangisidir?',
      options: ['Salyangoz', 'örümcek', 'ayı', 'koala', 'aslan'],
      answer: 'Salyangoz',
    },
    {
      id: 9,
      question:
        'Eski Yunan da erkekler kadınlara hislerini belli etmek için aşağıdakilerden hangisini yaparlardı?',
      options: [
        'Taş Yontmak',
        'Elma Atmak',
        'Şiir yazmak',
        'Çiçek vermek',
        'Sakallarını kesmek',
      ],
      answer: 'Elma Atmak',
    },
  ],
  g6: [
    {
      id: 0,
      question: 'İlk kadın arkeolog kimdir?',
      options: [
        'Jale İnan',
        'Rukiye Kanat Arran',
        'Aysel Gönül Öymen',
        'Esma Deniz',
        'Güler Karakülah',
      ],
      answer: 'Jale İnan',
    },
    {
      id: 1,
      question:
        '2018`de UNESCO Dünya Miras Geçici Listesine dahil edilen Anadolu`nun Pompeisi olarak görülen `Priene Antik Kenti` hangi ilimizdedir?',
      options: ['İzmir', 'Bayburt', 'Aydın', 'Muğla', 'Çorum'],
      answer: 'Aydın',
    },
    {
      id: 2,
      question: 'İstanbulu ilk kuşatan Osmanlı padişahı kimdir?',
      options: [
        'Orhan Gazi',
        'Osman Gazi',
        '4.Murad',
        '1.Selim',
        'Yıldırım Beyazid',
      ],
      answer: 'Yıldırım Beyazid',
    },
    {
      id: 3,
      question: 'İlk milli savaş gemimizin adı aşağıdakilerden hangisidir?',
      options: ['Heybeliada', 'Piri Reis', 'Kızıl Reis', 'Göktürk', 'Atak'],
      answer: 'Heybeliada',
    },
    {
      id: 4,
      question: 'Türkiye`nin ilk sismik araştırma gemisinin adı nedir?',
      options: [
        'Marmara',
        'Mavi Marmara',
        'Oruç Reis',
        'Hayrettin Paşa',
        'Milgem',
      ],
      answer: 'Oruç Reis',
    },
    {
      id: 5,
      question:
        'Tam olarak Türk yapımı olan keskin nişancı tüfeğinin adı nedir?',
      options: ['MPT-55', 'MPT76', 'Umtaş', 'Atak', 'Bora-12'],
      answer: 'Bora-12',
    },
    {
      id: 6,
      question:
        '2019`da yapılan eurovision yarışmasında 1. olan ülke aşağıdakilerden hangisidir?',
      options: ['Fransa', 'Türkiye', 'Yunanistan', 'Hollanda', 'İngiltere'],
      answer: 'Hollanda',
    },
    {
      id: 7,
      question:
        'İslami dayanışma oyunları 2021 yılında hangi ülkede düzenlenecek?',
      options: ['Kazakistan', 'Türkiye', 'Arabistan', 'Katar', 'Azerbaycan'],
      answer: 'Türkiye',
    },
    {
      id: 8,
      question:
        'Çin`in Ay`da ilk kez denenen biyolojik yetiştiricilikte bir ilk başarıp yetiştirdiği tarım ürünü nedir?',
      options: ['Pirinç', 'Mısır', 'Kuru Fasulye', 'Arpa', 'Pamuk'],
      answer: 'Pamuk',
    },
    {
      id: 9,
      question: '2019 Dünya Bankası başkanı kimdir?',
      options: [
        'Arthur Leffer',
        'Wilbur Ross',
        'christen Lagarde',
        'David Malpass',
        'Stephan Moore',
      ],
      answer: 'David Malpass',
    },
  ],
  g7: [
    {
      id: 0,
      question:
        'Uluslararası Bahçe Bitkileri Üreticileri Birliği tarafından organie edilen expo 2023 nerede düzenlenecek?',
      options: ['yozgat', 'bayburt', 'rize', 'kahramanmaraş', 'giresun'],
      answer: 'kahramanmaraş',
    },
    {
      id: 1,
      question: '2019 FIBA Basketbol Dünya Kupası hangi ülkede yapılmıştır?',
      options: ['Çin', 'Türkiye', 'Rusya', 'ABD', 'İspanya'],
      answer: 'Çin',
    },
    {
      id: 2,
      question: 'Mimar Sinan`ın İstanbul`daki ilk eseri hangisidir?',
      options: [
        'Selimiye Camisi',
        '3.Selim Çeşmesi',
        'Sultan Ahmet Camisi',
        'Haseki külliyesi',
        'Süleymaniye Camisi',
      ],
      answer: 'Haseki külliyesi',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g8: [
    {
      id: 0,
      question: '--defaultg8-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g9: [
    {
      id: 0,
      question: '--defaultg9-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g10: [
    {
      id: 0,
      question: '--defaultg10-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g11: [
    {
      id: 0,
      question: '--defaultg11-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g12: [
    {
      id: 0,
      question: '--defaultg12-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g13: [
    {
      id: 0,
      question: '--defaultg13-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g14: [
    {
      id: 0,
      question: '--defaultg14-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g15: [
    {
      id: 0,
      question: '--defaultg15-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g16: [
    {
      id: 0,
      question: '--defaultg16-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g17: [
    {
      id: 0,
      question: '--defaultg17-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g18: [
    {
      id: 0,
      question: '--defaultg18-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g19: [
    {
      id: 0,
      question: '--defaultg19-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
  g20: [
    {
      id: 0,
      question: '--defaultg20-- where is the capital of Turkey',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'ankara',
    },
    {
      id: 1,
      question: 'g3who is the CEO of Tesla Motor',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Elon Mask',
    },
    {
      id: 2,
      question: 'g3what is the matrix?',
      options: ['a film', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'a film',
    },
    {
      id: 3,
      question: 'where is the capital of Yobazistan',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'yozgat',
    },
    {
      id: 4,
      question: 'who is the CEO of Grosery',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'Levent Uğurses',
        'fitil fitilov',
      ],
      answer: 'Levent Uğurses',
    },
    {
      id: 5,
      question: 'what is the Zira in Turkish?',
      options: ['dick', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'çukubik',
    },
    {
      id: 6,
      question: 'who is the CEO of Mesut Eğitim Kurumları',
      options: [
        'Mesut Topacık',
        'Elon Mask',
        'Steve Jobs',
        'ali veli örnek',
        'fitil fitilov',
      ],
      answer: 'Mesut Topacık',
    },
    {
      id: 7,
      question: 'what is the tshirt in turkish?',
      options: ['gömlek', 'simulation', 'visual reality', 'çukubik', 'fikubik'],
      answer: 'gömlek',
    },
    {
      id: 8,
      question: 'where is the capital of son of bitches',
      options: ['yozgat', 'bayburt', 'rize', 'ankara', 'giresun'],
      answer: 'rize',
    },
    {
      id: 9,
      question: 'who wants to fuck the turkish people',
      options: [
        'mesut topacık',
        'Elon Mask',
        'Steve Jobs',
        'cengiz piçi',
        'fitil fitilov',
      ],
      answer: 'cengiz piçi',
    },
  ],
};
